# Generated by Django 6.0.5 on 2026-05-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localizacao',
            name='endereco_aproximado',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
