# Generated by Django 6.0.5 on 2026-05-28 21:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_localizacao_endereco_aproximado'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='intensidade',
            field=models.PositiveSmallIntegerField(default=5, help_text='Intensidade da atividade de 1 (leve) a 10 (muito pesada).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
