# Generated by Django 6.0.5 on 2026-05-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_atividade_intensidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='descricao',
            field=models.TextField(default='', help_text='Descreva com clareza como essa atividade e executada no campo.'),
        ),
    ]
