# Generated by Django 6.0.5 on 2026-05-30 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_atividade_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='idade',
            field=models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='sexo',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outro', 'Outro'), ('nao_informado', 'Prefiro não informar')], default='nao_informado', max_length=20),
        ),
    ]
