# Generated by Django 6.0.5 on 2026-05-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_colaborador_idade_colaborador_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='detalhes_extras',
            field=models.TextField(blank=True, default='', help_text='Informe doencas, fatores psicologicos e outros cuidados relevantes do colaborador.'),
        ),
    ]
